name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: cargo build --workspace --all-targets --verbose